**Scalers**

In [1]:
#Scaler representing Temperature in celsius

temperature=25
print(f"The temperature is {temperature} c")

The temperature is 25 c


In [2]:
#A scaler representing a student's score in a test

score=85.5
print(f"The student's score is {score}")

The student's score is 85.5


**Vectors**

In [3]:
#A vector representing days of a week

day_of_week=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
print("Days of the week are",day_of_week)

Days of the week are ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']


In [4]:
#A vector representing monthly rainfall in millimeters

monthly_rainfall=[12,23,45,78,97,54,23,34,102]
print("Monthly Rainfall:",monthly_rainfall)


Monthly Rainfall: [12, 23, 45, 78, 97, 54, 23, 34, 102]


**Lists**

In [5]:
#A list containing different types of itmes

mixed_bag=[42,'banana',3.14,False]
print("Mixed Bag:",mixed_bag)


Mixed Bag: [42, 'banana', 3.14, False]


In [6]:
#A list representing a Student's Information

student_info=['John Doe',20,'Computer Science',3.5]
print("Student's information",student_info)

Student's information ['John Doe', 20, 'Computer Science', 3.5]


**Arrays**

In [7]:
import numpy as np

#A 2D array representing coordinates

coordinates=np.array([[1,2],[3,4],[5,6]])
print("Coordinates:\n",coordinates)

Coordinates:
 [[1 2]
 [3 4]
 [5 6]]


In [8]:
#A 2D array representating pixel intensities of a grapscale image

pixel_intensities=np.array([[255,128,0],[64,32,16],[8,4,2]])
print("Pixel intensities\n",pixel_intensities)

Pixel intensities
 [[255 128   0]
 [ 64  32  16]
 [  8   4   2]]


**Factors**

In [9]:
#A factor representing survey responses

import pandas as pd

responses=pd.Categorical(['Yes','No','Yes','No','Maybe'])
print("Survey Responses:",responses)

Survey Responses: ['Yes', 'No', 'Yes', 'No', 'Maybe']
Categories (3, object): ['Maybe', 'No', 'Yes']


In [10]:
#A factor representing shirt sizes

shirt_sizes=pd.Categorical(['S','M','L','XL','L'])
print("Shirt Sizes",shirt_sizes)

Shirt Sizes ['S', 'M', 'L', 'XL', 'L']
Categories (4, object): ['L', 'M', 'S', 'XL']


**Dataframe**

In [11]:
#A dataframe representing class Grades

grades_data={'Name':['Alice','Bob','Charlie'],
             'Math':[85,90,95],
             'Science':[92,88,85]}

grades_df=pd.DataFrame(grades_data)
print("Class Grades",grades_df)

Class Grades       Name  Math  Science
0    Alice    85       92
1      Bob    90       88
2  Charlie    95       85


In [12]:
#Reading Data from a CSV file

import pandas as pd
product_df=pd.read_csv('nj.csv')
print("Products from CSV\n",product_df)

#Analyzing data
print("Summary statistics\n",product_df.describe())
print("Data Types \n",product_df.dtypes)

FileNotFoundError: [Errno 2] No such file or directory: 'nj.csv'

**Working on Titanic Dataset**

Scaler

In [ ]:
#Importing neceddary Library
import pandas as pd

#Load th dataset
titanic_df=pd.read_csv('tested.csv')

#Scaler Representing number of passengers
num_passengers=len(titanic_df)
print(f"Number of passengers: {num_passengers}")

Number of passengers: 418


Vector

In [ ]:
#Vector Representing number of passengers
passenger_names=titanic_df['Name'].tolist()
print("First 5 passengers name",passenger_names[:5])
print("Last 5 passengers name",passenger_names[-5:])

First 5 passengers name ['Kelly, Mr. James', 'Wilkes, Mrs. James (Ellen Needs)', 'Myles, Mr. Thomas Francis', 'Wirz, Mr. Albert', 'Hirvonen, Mrs. Alexander (Helga E Lindqvist)']
Last 5 passengers name ['Spector, Mr. Woolf', 'Oliva y Ocana, Dona. Fermina', 'Saether, Mr. Simon Sivertsen', 'Ware, Mr. Frederick', 'Peter, Master. Michael J']


List

In [ ]:
#List Reprentation information of a first five passenger's
titanic = pd.read_csv('tested.csv')
names_passengers = titanic['Name'].tolist()
print("First 5 passengers: ",names_passengers[:5])

First 5 passengers:  ['Kelly, Mr. James', 'Wilkes, Mrs. James (Ellen Needs)', 'Myles, Mr. Thomas Francis', 'Wirz, Mr. Albert', 'Hirvonen, Mrs. Alexander (Helga E Lindqvist)']


Array

In [ ]:
import numpy as np
#Array represnting passenger ages
age_array=np.array(titanic_df['Age'].fillna(0))
print("First 5 passengers:",age_array[:5])

#Array represting passenger fares
fare_array=np.array(titanic_df['Fare'])
print("First 5 passenger fares",fare_array[:5])

First 5 passengers: [34.5 47.  62.  27.  22. ]
First 5 passenger fares [ 7.8292  7.      9.6875  8.6625 12.2875]


Matrix

In [ ]:
titanic = pd.read_csv('tested.csv')
Age = np.array(titanic['Age'].fillna(0))
print('First 5 passengers age:',Age[:5])

Fare = np.array(titanic['Fare'])
print('First 5 passengers Fares:',Fare[:5])

First 5 passengers age: [34.5 47.  62.  27.  22. ]
First 5 passengers Fares: [ 7.8292  7.      9.6875  8.6625 12.2875]


In [ ]:
titanic = pd.read_csv('tested.csv')
class_fac = pd.Categorical(titanic['Pclass'])
print("passenger class category: ",class_fac.categories)

embarked_fac = pd.Categorical(titanic['Embarked'].fillna('none'))
print('Embarked loc category: ',embarked_fac.categories)


passenger class category:  Index([1, 2, 3], dtype='int64')
Embarked loc category:  Index(['C', 'Q', 'S'], dtype='object')


In [ ]:
titanic = pd.read_csv('tested.csv')
print("First 5 row of titanic dataframe:\n",titanic.head())
print("\nDataFrame info: ")
print(titanic.info)
print("\n Summary stats: \n",titanic.describe())

First 5 row of titanic dataframe:
    PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S  

DataFrame info: 
<bound method DataFrame.info of  